name: MLflow CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Train model with MLflow
      run: |
        python models/train_model.py
    
    - name: Save metrics
      run: |
        mkdir -p mlflow_output
        python models/train_model.py
        cat mlflow_output/metrics.txt
    
    - name: Upload metrics as artifact
      uses: actions/upload-artifact@v3
      with:
        name: model-metrics
        path: mlflow_output/metrics.txt